Name = input("What is your Name ")
Branch = input("What is your Branch ")
College = input("What is your college Name ")
Gender = input("What is your Gender ")
Age = input("What is your Age ")
print(Name + "\n" + Branch + "\n" + College + "\n" + Gender + "\n" + Age)